#!/bin/bash

# Server Setup & Deployment Script
# This script sets up a fresh VPS and deploys your fullstack app

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}🚀 Fullstack App Deployment Script${NC}"
echo "====================================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}Please run as root (use sudo)${NC}"
    exit 1
fi

# Get deployment parameters
if [ -z "$1" ]; then
    echo -e "${RED}Usage: sudo ./deploy.sh <domain>${NC}"
    echo "Example: sudo ./deploy.sh myapp.dev"
    exit 1
fi

DOMAIN=$1
APP_DIR="/home/ubuntu/app"

echo -e "${YELLOW}Setting up server for: ${DOMAIN}${NC}"

# Step 1: Update system
echo -e "${GREEN}Step 1: Updating system packages...${NC}"
apt-get update
apt-get upgrade -y

# Step 2: Install Docker
if ! command -v docker &> /dev/null; then
    echo -e "${GREEN}Step 2: Installing Docker...${NC}"
    curl -fsSL https://get.docker.com | sh
    systemctl enable docker
    systemctl start docker
    usermod -aG docker ubuntu
else
    echo -e "${YELLOW}Docker already installed, skipping...${NC}"
fi

# Step 3: Install Docker Compose
if ! command -v docker-compose &> /dev/null; then
    echo -e "${GREEN}Step 3: Installing Docker Compose...${NC}"
    apt-get install -y docker-compose-plugin
else
    echo -e "${YELLOW}Docker Compose already installed, skipping...${NC}"
fi

# Step 4: Configure firewall
echo -e "${GREEN}Step 4: Configuring firewall...${NC}"
ufw allow 22/tcp   # SSH
ufw allow 80/tcp   # HTTP
ufw allow 443/tcp  # HTTPS
ufw --force enable

# Step 5: Create app directory
echo -e "${GREEN}Step 5: Setting up application directory...${NC}"
mkdir -p $APP_DIR
chown -R ubuntu:ubuntu $APP_DIR

# Step 6: Clone or copy application files
echo -e "${GREEN}Step 6: Deploying application...${NC}"
cd $APP_DIR

# If .env doesn't exist, create it
if [ ! -f ".env" ]; then
    echo -e "${YELLOW}Creating .env file...${NC}"
    cat > .env << EOF
# Generated by deployment script
DOMAIN=${DOMAIN}
NODE_ENV=production
EOF
fi

# Step 7: Start application
echo -e "${GREEN}Step 7: Starting Docker containers...${NC}"
docker compose pull
docker compose build
docker compose up -d

# Step 8: Wait for services to be ready
echo -e "${GREEN}Step 8: Waiting for services to start...${NC}"
sleep 10

# Check if services are running
if docker compose ps | grep -q "Up"; then
    echo -e "${GREEN}✅ All services are running!${NC}"
else
    echo -e "${RED}⚠️  Some services failed to start. Check logs with: docker compose logs${NC}"
fi

# Step 9: Display status
echo ""
echo -e "${GREEN}🎉 Deployment Complete!${NC}"
echo "====================================="
echo -e "Your app is accessible at:"
echo -e "  ${GREEN}https://${DOMAIN}${NC}"
echo ""
echo -e "Useful commands:"
echo -e "  ${YELLOW}docker compose logs -f${NC}     # View logs"
echo -e "  ${YELLOW}docker compose ps${NC}          # Check status"
echo -e "  ${YELLOW}docker compose restart${NC}     # Restart services"
echo -e "  ${YELLOW}docker compose down${NC}        # Stop services"
echo ""

# Optional: Setup automatic updates with GitHub Actions
echo -e "${YELLOW}📝 Next step: Setup GitHub Actions${NC}"
echo "Add these secrets to your GitHub repository:"
echo "  - HOST: $(curl -s ifconfig.me)"
echo "  - USERNAME: ubuntu"
echo "  - SSH_KEY: (your private SSH key)"
echo ""
echo "Then push to main branch to auto-deploy!"
